# Generated by Django 3.2.9 on 2021-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumnno', models.CharField(max_length=50)),
                ('correo_alumno', models.CharField(max_length=40)),
                ('password_alumno', models.CharField(max_length=30)),
            ],
        ),
    ]
